plugins:
  - rubocop-performance
  - rubocop-rails
  - rubocop-slim
  - rubocop-rspec

RSpec/NamedSubject:
  Enabled: false

RSpec/ExampleLength:
  Max: 7

RSpec/MultipleExpectations:
  Max: 3

RSpec/NestedGroups:
  Max: 4

RSpec/MessageSpies:
  Enabled: false

Metrics:
  Enabled: false

Layout:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

AllCops:
  NewCops: disable
  SuggestExtensions: false
